ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS tags text[] NOT NULL DEFAULT '{}';

INSERT INTO public.posts (author_id, title, slug, excerpt, content, cover_image_url, category, location, tags, published, published_at)
SELECT u.id, v.title, v.slug, v.excerpt, v.content, v.cover, v.category, v.location, v.tags, true, v.pub
FROM (SELECT id FROM auth.users WHERE email = 'charles.hsieh6@gmail.com' LIMIT 1) u,
(VALUES
 ('Slow mornings on the Atlantic coast','slow-mornings-atlantic-coast','Three weeks of cliff roads, pastel de nata, and letting the kids set the pace.',
  '<p>We landed in Lisbon with a loose plan and two kids who had already decided that jet lag was optional. By the second morning we had given up on the itinerary entirely, which turned out to be the best decision of the trip.</p><h2>Letting the day arrive</h2><p>Every morning started the same way: coffee at the counter, pastries eaten standing up, and a slow walk to wherever the light looked good. We stopped measuring days in sights and started measuring them in hours spent outside.</p><figure><img src="/img/posts/portugal-inline.jpg" alt="Pastel de nata and espresso on a tiled cafe table" /><figcaption>Breakfast, most days.</figcaption></figure><h2>What changed</h2><p>Traveling with small kids forces a pace that I would never choose on my own, and it turns out that pace is better. We saw less and remembered more.</p><blockquote>The trip we planned would have been more efficient. The trip we took is the one the kids still talk about.</blockquote>',
  '/img/posts/portugal-cover.jpg','travel','Lisbon, Portugal', ARRAY['Family trip','Slow travel'], now() - interval '9 days'),
 ('Lantern light in the back streets','lantern-light-back-streets','Notes on eating standing up, riding trains with a toddler, and getting lost on purpose.',
  '<p>Japan rewards wandering more than any place I have been. The plan was three neighborhoods a day. What actually happened was one alley, repeated.</p><h2>Dinner at a counter</h2><p>Half our best meals were at counters with six seats and no English menu. You point, you nod, you eat something better than anything you would have found by searching.</p><figure><img src="/img/posts/japan-inline.jpg" alt="A small ramen counter seen from the street" /><figcaption>Six seats, one cook, no menu we could read.</figcaption></figure><p>The trains were the surprise. A toddler and a rush-hour transfer sound like a disaster, and instead it was the calmest commute of my life.</p>',
  '/img/posts/japan-cover.jpg','travel','Kyoto, Japan', ARRAY['Food & wandering','City walks'], now() - interval '24 days'),
 ('Red rock, dirt roads, no signal','red-rock-dirt-roads-no-signal','A week through canyon country, and why losing connectivity was the most useful thing I did all year.',
  '<p>We drove nine hundred miles with no plan past the next campsite. Somewhere on day two the phone gave up entirely, and I stopped reaching for it by day three.</p><h2>The quiet part</h2><p>Without a signal there is nothing to do in the gaps except look out the window and talk. We talked more in that week than in the previous three months.</p><p>I came home with a notebook full of ideas, half of which were bad, and one that turned into a real project.</p>',
  '/img/posts/southwest-cover.jpg','travel','Moab, Utah', ARRAY['Road trip','Offline'], now() - interval '48 days'),
 ('What a year of writing every morning actually changed','a-year-of-morning-pages','I put a notebook on the counter to get thoughts out of my head before the house woke up. Here is what stuck.',
  '<p>It started as a way to stop lying awake at 5am with a running list. A notebook on the kitchen counter, a pen next to it, and a rule that I was not allowed to open anything with a screen first.</p><h2>What stuck</h2><ul><li>Writing before input. No email, no feed, no news.</li><li>Twenty minutes, not an hour. The hour version never survived a busy week.</li><li>No editing. The point is the thinking, not the sentences.</li></ul><h2>What did not</h2><p>Every attempt to make it a system failed. Templates, prompts, tracking streaks, all of it collapsed within a month. The only version that lasted was the boring one.</p><blockquote>Most of what I wrote is unusable. A handful of pages turned into projects I am still working on.</blockquote>',
  '/img/posts/morning-pages-cover.jpg','writing',NULL, ARRAY['Habits','Writing'], now() - interval '5 days'),
 ('Building things on nights and weekends','building-nights-and-weekends','Why I keep starting projects I do not have time for, and the rules that keep them from eating my life.',
  '<p>I have a bad habit of building the thing instead of writing the memo about the thing. Most of it never ships. Some of it becomes the most interesting work I do.</p><h2>The rules</h2><ul><li>It has to be something I would use myself.</li><li>Ship an ugly version within two weekends or drop it.</li><li>Never let it compete with dinner.</li></ul><p>The rules are not about productivity. They are about making sure the side project stays the fun part instead of turning into a second job I did not ask for.</p>',
  '/img/posts/building-cover.jpg','writing',NULL, ARRAY['Building','Side projects'], now() - interval '19 days'),
 ('The sabbatical year reset everything','sabbatical-year-reset','A year off changed how I think about work, time, and what a good week actually looks like.',
  '<p>I did not take a sabbatical to find myself. I took one because I was tired and out of ideas, and both of those are cheaper to fix with time than with a new job.</p><h2>What a good week looks like now</h2><p>Mornings that are mine, work that has an end, and at least one afternoon that nobody scheduled. It sounds soft. It is the most productive I have ever been.</p><p>The hardest part was not the money. It was the first two months of not being useful to anyone, and learning that the discomfort was the whole point.</p>',
  '/img/posts/sabbatical-cover.jpg','writing',NULL, ARRAY['Sabbatical','Work'], now() - interval '40 days')
) AS v(title, slug, excerpt, content, cover, category, location, tags, pub)
WHERE NOT EXISTS (SELECT 1 FROM public.posts p WHERE p.slug = v.slug);